name: studio_crow
description: Studio Crow - Luxury Studio & Member Management Application for Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  share_plus: ^7.2.1
  intl: ^0.18.1
  google_sign_in: ^6.2.1
  http: ^1.2.0
  path: ^1.9.0
  workmanager: ^0.10.7
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
